# Solving n-degree Polynomial
For polynomials up to degree 4, there are explicit solution formulas similar to that for the quadratic equation (the Cardano formulas for third-degree equations, and the Ferrari formula for degree 4).

For higher degrees, no general formula exists (or more precisely, no formula in terms of addition, subtraction, multiplication, division, arbitrary constants and nn-th roots). This result is proved in Galois theory and is known as the [Abel-Ruffini theorem](https://en.wikipedia.org/wiki/Abel%E2%80%93Ruffini_theorem).

Linear Algebra to rescue, we can find roots of univariate polynomials via eigenvalues/eigenvectors of companion matrices. [Read More](www.jhuapl.edu/techdigest/TD/td2804/Williams.pdf)

In [1]:
import numpy as np
from IPython.display import Latex

In [2]:
def solve(*coefficients): #take any number of coefficients, as a tuple
    '''Here the k = -1, this means the first row will be padded with zeros and the identity-matrix-like-look
        will appear from the second row, that is how a companion matrix looks like.
        Read more: https://en.wikipedia.org/wiki/Companion_matrix '''
    companion = np.eye(len(coefficients) - 1, k=-1) #to be, companion matrix
    
    '''Filling the last column of matrix to make a companion matrix.
        This requires the coefficient of highest degree to be 1, so diving by co-of highest degree,
        then adding the negatives to coefficients to last column. Such that,
        Highest-to-Lowest degree are bottom-to-top in column'''
    companion[:,-1] = -np.array(coefficients[:0:-1]) / coefficients[0]
    
    return np.linalg.eigvals(companion) #return eigen values of companion matrix, the roots of p(x)

#### Tests

1. $\quad 2x^{3} + 7x^{2} + 4x - 4 = 0$
2. $\quad x^{5} + 8x^{4} + 2x^{3} - 4x^{2} + 14x + 6 = 0$
3. $\quad 4x^{2} + 6x = 0$

In [3]:
solve(2, 7, 4, -4)

array([ 0.5       , -2.00000002, -1.99999998])

In [4]:
solve(1, 8, 2, -4, 14, 6)

array([ 0.73770613+0.92237007j,  0.73770613-0.92237007j,
       -0.38932400+0.j        , -1.44602626+0.j        , -7.64006200+0.j        ])

In [5]:
solve(4, 6, 0)

array([-1.5,  0. ])